# Imports

In [1]:
import numpy as np
import pandas as pd 

# Question 1
What's the version of NumPy that you installed?

You can get the version information using the __version__ field:

In [2]:
np.__version__

'1.21.6'

# Getting the data

In [3]:
cars = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv")

In [4]:
cars.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

# Question 2
How many records are in the dataset?

In [5]:
print(f'There are {cars.shape[0]} rows.')

There are 11914 rows.


# Question 3
Who are the most frequent car manufacturers (top-3) according to the dataset?

In [6]:
cars['Make'].value_counts().index[0:3]

Index(['Chevrolet', 'Ford', 'Volkswagen'], dtype='object')

# Question 4
What's the number of unique Audi car models in the dataset?

In [7]:
cars[cars['Make'] == 'Audi']['Model'].nunique()

34

# Question 5
How many columns in the dataset have missing values?

In [8]:
cars.isna().any().sum()

5

# Question 6


1. Find the median value of "Engine Cylinders" column in the dataset.
2. Next, calculate the most frequent value of the same "Engine Cylinders".
3. Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
4. Now, calculate the median value of "Engine Cylinders" once again.
Has it changed?

> Hint: refer to existing mode and median functions to complete the task.

In [9]:
# Find the median value of "Engine Cylinders" column in the dataset.
median_cyl = cars['Engine Cylinders'].median()
median_cyl

6.0

In [10]:
# Calculate the most frequent value of the same "Engine Cylinders".
mode_cyl = cars['Engine Cylinders'].mode()[0]
mode_cyl

4.0

In [11]:
# Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
cars['Engine Cylinders'].fillna(mode_cyl).median()

6.0

The median remained the same even after filling missing values with the median.

Question 7
1. Select all the "Lotus" cars from the dataset.
2. Select only columns "Engine HP", "Engine Cylinders".
3. Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Compute the inverse of XTX.
7. Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9. What's the value of the first element of w?

> Note: You just implemented linear regression. We'll talk about it in the next lesson.

In [12]:
# Select all the "Lotus" cars from the dataset.
lotus_cars = cars[cars['Make'] == 'Lotus']
lotus_cars.head(2)

Make  Model  Year             Engine Fuel Type  Engine HP  \
3912  Lotus  Elise  2009  premium unleaded (required)      189.0   
3913  Lotus  Elise  2009  premium unleaded (required)      218.0   

      Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
3912               4.0            MANUAL  rear wheel drive              2.0   
3913               4.0            MANUAL  rear wheel drive              2.0   

              Market Category Vehicle Size Vehicle Style  highway MPG  \
3912  Exotic,High-Performance      Compact   Convertible           27   
3913  Exotic,High-Performance      Compact   Convertible           26   

      city mpg  Popularity   MSRP  
3912        21         613  43995  
3913        20         613  54990

In [13]:
# Select only columns "Engine HP", "Engine Cylinders".
lotus_cars = lotus_cars[["Engine HP", "Engine Cylinders"]]

In [14]:
# Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
lotus_cars = lotus_cars.drop_duplicates()
lotus_cars

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [15]:
# Get the underlying NumPy array. Let's call it X.
X = lotus_cars.values
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [16]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. 
# Let's call the result XTX.
XTX = X.T @ X
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [17]:
# Compute the inverse of XTX.
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [18]:
# Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = (XTX_inv @ X.T) @ y

# What's the value of the first element of w?
w[0]

4.594944810094551